### PR TITLE
Allow for fuzzy match of assembly summary header

### LINKED ISSUE #209: KeyError: 'assembly_accession'
Hi!

Version :
```
ncbi-genome-download --version
0.3.1
```

Command :
```
ncbi-genome-download \
    -s genbank -A GCA_029448725.1 --formats fasta all \
     \
    --output-folder ./ \
    --flat-output
```

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ncbi-genome-download", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/usr/local/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 178, in args_download
    return config_download(config)
  File "/usr/local/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 197, in config_download
    download_candidates = select_candidates(config)
  File "/usr/local/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 308, in select_candidates
    for entry in filter_entries(entries, config):
  File "/usr/local/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 354, in filter_entries
    if not config.is_compatible_assembly_accession(entry['assembly_accession']):
KeyError: 'assembly_accession'
```

Very similar to this older issue : https://github.com/kblin/ncbi-genome-download/issues/2

### PR DESCRIPTION
**Pull request by chasemc**
fixes #209

### CODE REVIEW

**Comment by chasemc** [comment]
@SolMiele  Did you try installing this pull request?
e.g.
```
pip uninstall ncbi-genome-download
pip install git+https://github.com/chasemc/ncbi-genome-download@4c5c24e27aa8123c7995890046b17b815da3571b
```

Note: I have fully tested it but it did work with `ncbi-genome-download -s refseq --assembly-accessions GCF_000525635.1 bacteria`

**Comment by andrewjpage** [comment]
It works for me and downloaded 40,000 bacterial genomes from genbank and refseq

**Comment by 1185307269** [comment]
Hello! I tried this :

**_pip uninstall ncbi-genome-download_**

**_pip install git+https://github.com/chasemc/ncbi-genome-download@4c5c24e27aa8123c7995890046b17b815da3571b_**

and my command like this:

_**ncbi-genome-download --assembly-accessions "GCA_001951075.2"  bacteria,archaea -l "complete" --section genbank --formats fasta --flat-output -o ./**_


but it does not work. So , what should I do ? Can you hepl me ?  The same error as https://github.com/kblin/ncbi-genome-download/issues/209, is it fixed?

**Comment by nush320** [comment]
Hello, I tried the `pip uninstall ncbi-genome-download
pip install git+https://github.com/chasemc/ncbi-genome-download@4c5c24e27aa8123c7995890046b17b815da3571b`

and then tried 'ncbi-genome-download --genera Streptomyces bacteria --dry-run | head' 

Seems to be working to some point but I also get an error message at the end. @ialbert Please see the following. Using `NCBI-genome-download --genera Streptomyces bacteria --dry-run | head` - capital letters for NCBI as in the handbook still says command not found.

```
Considering the following 2815 assemblies for download:
GCF_003208035.1 Streptomyces actuosus   ATCC 25421
GCF_016921115.1 Streptomyces actuosus   VRA1
GCF_000156475.1 Streptomyces albidoflavus       J1074
GCF_000359525.1 Streptomyces albidoflavus       J1074
GCF_000719495.1 Streptomyces albidoflavus       NRRL F-5621
GCF_000719435.1 Streptomyces albidoflavus       NRRL F-5618
GCF_000719955.1 Streptomyces albidoflavus       NRRL B-1271
GCF_000717375.1 Streptomyces albidoflavus       NRRL B-2307
GCF_001509565.1 Streptomyces albidoflavus       NRRL WC-3066
Traceback (most recent call last):
  File "/home/bstarnush/miniconda3/bin/ncbi-genome-download", line 8, in <module>
    sys.exit(main())
  File "/home/bstarnush/miniconda3/lib/python3.10/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/home/bstarnush/miniconda3/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 184, in args_download
    return config_download(config)
  File "/home/bstarnush/miniconda3/lib/python3.10/site-packages/ncbi_genome_download/core.py", line 212, in config_download
    print(entry['assembly_accession'], entry['organism_name'], get_strain(entry), sep="\t")
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by chasemc** [comment]
The proposed fix should work, so it's likely that it's an issue with installing the PR.

Python is pretty notoriously difficult when dealing with package versions and I'm no expert pip's installation details but that's likely why it seems it's not working.

Change the my_directory variable below to point to a path on your computer
```
my_directory='/home/chase/Downloads/ncbi-genome-download'

python3 -m venv dl $my_directory
source $my_directory
pip install git+https://github.com/chasemc/ncbi-genome-download@4c5c24e27aa8123c7995890046b17b815da3571b 
```

Then `$my_directory`  will have a `bin` directory containing  ncbi-genome-download
Use the activated environment to run it or by using the path directly
e.g.  `$my_directory/bin/ncbi-genome-download`

**Comment by chasemc** [comment]
@nush320 that is a different issue related to implementation (without the pipe to `head` should work)
see https://docs.python.org/3/library/signal.html#note-on-sigpipe

**Comment by rpetit3** [comment]
@chasemc as a temporary solution I used your changes to patch the Bioconda recipe

**Comment by kblin** [comment]
Thanks for this, I ended up solving it slightly different in bd4607102748673c2f2e45719213b74fda37b606. Should be fixed in 0.3.2

**Pull request closed without merging**
