### PR TITLE
Handle IndexError when value for organism_name is abnormal

### PR DESCRIPTION
**Pull request by andrewsanchez**
Addresses another instance of #29

### CODE REVIEW

**Comment by kblin** [comment]
Hi, thanks for your contribution! I'd like to add a test to make sure the code path stays functional, then it should be ready to go.

**Comment by andrewsanchez** [comment]
@kblin I'd be happy to try adding the test myself if you'd point me in the right direction.  I'm keen on getting more familiar with the code base and this could be a good opportunity to do so.

**Comment by kblin** [comment]
Hi Andrew, sorry for the slow response, I've been super-busy with work recently.

The basic test I would add for the code would contain no space in the `organism_name`. Before your patch, that should raise an `IndexError` in `get_species_label`, and after the patch would be fine.

In `tests/test_core.py` there is a function `test_get_species_label`. You'd add another test case to it, maybe like:
```python
    fake_entry = {'organism_name': 'ExampleSpeciesWithoutSpace'}
    assert core.get_species_label(fake_entry) == 'ExampleSpeciesWithoutSpace'
```

Hope this helps,
Kai

**Comment by kblin** [comment]
Hi there,
Sorry, this fell off my radar completely, and now I fixed this myself by accident in e78bcbb.
I like returning `sp.` better than just repeating the organism name again, so I'll keep my version.
Thank you for your contribution anyway, and sorry it took so long for me to act on it.

**Pull request closed without merging**
